### PR TITLE
Sets title as an empty string if no reference is found. Fixes #2

### LINKED ISSUE #2: Component does not fail gracefully when a section title cannot be found
https://github.com/metal/metal-reading-progress/blob/master/src/ReadingProgress.js#L35

When this querySelector returns null an error is thrown. It would be nice if it either passes an empty string as the title or throws a more helpful error.

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

File: src/ReadingProgress.js [hunk 1]
```diff
@@ -32,7 +32,11 @@ class ReadingProgress extends Component {
 
 		var element = document.getElementById(item.href.substr(1));
 		if (!item.title) {
-			item.title = element.querySelector(this.titleSelector).textContent;
+			item.title = '';
```
Comment (brunobasto) [inline src/ReadingProgress.js]: I think I would put this on an else statement:

```
if (titleElement) {
    item.title = titleElement.textContent;
}
else {
    item.title = '';
}
```

or maybe a ternary operator:

`item.title = titleElement ? ttileElement.textContent : '';`

I know this is really picky, but this way we have only one variable assignment instead of two consecutive ones.

Comment (jbalsas) [reply src/ReadingProgress.js]: I like this better as well :)

Comment (fernandosouza) [reply src/ReadingProgress.js]: Branch update, guys. Thx. 😃

**Comment by robframpton** [comment]
LGTM

**Review by robframpton — APPROVED** [review]

**Comment by brunobasto** [comment]
LGTM
